This repository contains libraries needed to make SuperCollider run on EMACS plus a script for linking these to the appropriate places on a RaspBerry Pi, and an emacs-lisp file for setting the configuration needed to run SuperCollider on EMACS.

- scemacs :: SuperCollider Library for connecting to EMACS.
- sclang :: Emacs Library for connecting to SuperCollider.
- sclang/install.el : Script for installing this library on a raspberry pi

* Installation

On your raspberry pi shell, get the library from GitHub:

: cd ~/ # switch to home directory
: git clone https://github.com/iani/pimacsc.git # download the library from GitHub

On emacs, evaluate the following expression to load the install script:

: (load-file "/home/pi/pimacsc/sclang/install.el")

This links the library for SuperCollider which you downloaded from github to the required place in the SuperCollider Extensions folder, and loads the EMACS library.  This setting will last only for the current session.  To reload the required EMACS library every time that you start EMACS, place the line: 

#+BEGIN_SRC bash
(load-file "/home/pi/pimacsc/sclang/install.el")
#+END_SRC

somewhere in your init file.

* Booting the server on Raspberry Pi

To boot the server, jack audio server must be running.  Before doing

: Server.default.boot

start jack from the command line by running:

: jackd -P75 -dalsa -dhw:0 -p1024 -n3 -s -r44100

edit -dhw:0 to match your soundcard.  0 is built-in output. 1 is usually USB.

After that, you can boot the default server on the SC Workspace by running:

: Server.default.boot
